#!/usr/bin/env bash

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest

echo "
if (file_exists(\$app_root . '/' . \$site_path . '/settings.local.php')) {
    include \$app_root . '/' . \$site_path . '/settings.local.php';
}" >> ${SITEDIR_PATH}/settings.php

	else
		echo "${dest} already in place."
	fi
}

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
	chmod 766 "${SITEDIR_PATH}/settings.php"
}

#-------------------------- END: Helper functions --------------------------------

fin exec composer install
fix_permissions

# Copy from settings templates
copy_settings_file "${PROJECT_ROOT}/.docksal/etc/drupal_defaults/default.settings.local.php" "${SITEDIR_PATH}/settings.local.php"

fin db import "${PROJECT_ROOT}/.docksal/etc/dump/init.sql"

fin drush config-import sync -y

fin drush cr